/* Generated By:JJTree: Do not edit this line. ASTArrayAssignmentStatement.java */

public class ASTArrayAssignmentStatement extends SimpleNode {
  public ASTArrayAssignmentStatement(int id) {
    super(id);
  }

  public ASTArrayAssignmentStatement(MiniJavaParser p, int id) {
    super(p, id);
  }

}
