/* Generated By:JJTree: Do not edit this line. ASTAssignmentStatement.java */

public class ASTAssignmentStatement extends SimpleNode {
  public ASTAssignmentStatement(int id) {
    super(id);
  }

  public ASTAssignmentStatement(MiniJavaParser p, int id) {
    super(p, id);
  }

}
