/* Generated By:JJTree: Do not edit this line. ASTClassDeclaration.java */

public class ASTClassDeclaration extends SimpleNode {
  public ASTClassDeclaration(int id) {
    super(id);
  }

  public ASTClassDeclaration(MiniJavaParser p, int id) {
    super(p, id);
  }

}
