/* Generated By:JJTree: Do not edit this line. ASTGoal.java */

public class ASTGoal extends SimpleNode {
  public ASTGoal(int id) {
    super(id);
  }

  public ASTGoal(MiniJavaParser p, int id) {
    super(p, id);
  }

  
  public void generateRelations()
  {
		System.out.println( getClass().toString() );
  		super.generateRelations( );
//	  System.out.println( getClass().toString() );
//	  
//	  int child_count=jjtGetNumChildren( );
//	  for( int i=0; i<child_count; i++ )
//	  {
//		  	this.jjtGetChild(i).generateRelations( );
//	  }
  }
}
