/* Generated By:JJTree: Do not edit this line. ASTMainClass.java */

public class ASTMainClass extends SimpleNode {
  public ASTMainClass(int id) {
    super(id);
  }

  public ASTMainClass(MiniJavaParser p, int id) {
    super(p, id);
  }

  	public void generateRelations( )
  	{
  		System.out.println( getClass().toString() );
  		super.generateRelations( );
  	}
}
