/* Generated By:JJTree: Do not edit this line. ASTMessageSend.java */

public class ASTMessageSend extends SimpleNode {
  public ASTMessageSend(int id) {
    super(id);
  }

  public ASTMessageSend(MiniJavaParser p, int id) {
    super(p, id);
  }

}
