/* Generated By:JJTree: Do not edit this line. ASTSimpleNode.java */

public class ASTSimpleNode extends SimpleNode {
  public ASTSimpleNode(int id) {
    super(id);
  }

  public ASTSimpleNode(MiniJavaParser p, int id) {
    super(p, id);
  }

}
