/* Generated By:JJTree: Do not edit this line. ASTTypeDeclaration.java */

public class ASTTypeDeclaration extends SimpleNode {
  public ASTTypeDeclaration(int id) {
    super(id);
  }

  public ASTTypeDeclaration(MiniJavaParser p, int id) {
    super(p, id);
  }
  
	public void generateRelations( )
  	{
  		System.out.println( getClass().toString() );
//  		super.generateRelations( );
  	}
	
}
