/* Generated By:JJTree: Do not edit this line. ASTThisExpression.java */

public class ASTThisExpression extends SimpleNode {
  public ASTThisExpression(int id) {
    super(id);
  }

  public ASTThisExpression(MiniJavaParser p, int id) {
    super(p, id);
  }

}
