/* Generated By:JJTree: Do not edit this line. ASTWhileStatement.java */

public class ASTWhileStatement extends SimpleNode {
  public ASTWhileStatement(int id) {
    super(id);
  }

  public ASTWhileStatement(MiniJavaParser p, int id) {
    super(p, id);
  }

}
