package edu.ucla.parser.miniJava.javacc;

/* Generated By:JJTree: Do not edit this line. ASTArrayAllocationExpression.java */

public class ASTArrayAllocationExpression extends SimpleNode {
  public ASTArrayAllocationExpression(int id) {
    super(id);
  }

  public ASTArrayAllocationExpression(MiniJavaParser p, int id) {
    super(p, id);
  }

}
