package edu.ucla.parser.miniJava.javacc;

/* Generated By:JJTree: Do not edit this line. ASTClassExtendsDeclaration.java */

public class ASTClassExtendsDeclaration extends SimpleNode {
  public ASTClassExtendsDeclaration(int id) {
    super(id);
  }

  public ASTClassExtendsDeclaration(MiniJavaParser p, int id) {
    super(p, id);
  }

}
