package edu.ucla.parser.miniJava.javacc;

/* Generated By:JJTree: Do not edit this line. ASTExpression.java */

public class ASTExpression extends SimpleNode {
  public ASTExpression(int id) {
    super(id);
  }

  public ASTExpression(MiniJavaParser p, int id) {
    super(p, id);
  }

}
