package edu.ucla.parser.miniJava.javacc;

/* Generated By:JJTree: Do not edit this line. ASTType.java */

public class ASTType extends SimpleNode {
  public ASTType(int id) {
    super(id);
  }

  public ASTType(MiniJavaParser p, int id) {
    super(p, id);
  }

}
