/* Generated By:JJTree: Do not edit this line. ./MiniJavaParserTreeConstants.java */

package edu.ucla.parser.miniJava.javacc;

public interface MiniJavaParserTreeConstants
{
  public int JJTGOAL = 0;
  public int JJTMAINCLASS = 1;
  public int JJTTYPEDECLARATION = 2;
  public int JJTCLASSDECLARATION = 3;
  public int JJTCLASSEXTENDSDECLARATION = 4;
  public int JJTVARDECLARATION = 5;
  public int JJTMETHODDECLARATION = 6;
  public int JJTVOID = 7;
  public int JJTFORMALPARAMETER = 8;
  public int JJTTYPE = 9;
  public int JJTARRAYTYPE = 10;
  public int JJTSTATEMENT = 11;
  public int JJTBLOCK = 12;
  public int JJTASSIGNMENTSTATEMENT = 13;
  public int JJTARRAYASSIGNMENTSTATEMENT = 14;
  public int JJTIFSTATEMENT = 15;
  public int JJTWHILESTATEMENT = 16;
  public int JJTEXPRESSION = 17;
  public int JJTMESSAGESEND = 18;
  public int JJTPRIMARYEXPRESSION = 19;
  public int JJTTHISEXPRESSION = 20;
  public int JJTARRAYALLOCATIONEXPRESSION = 21;
  public int JJTALLOCATIONEXPRESSION = 22;


  public String[] jjtNodeName = {
    "Goal",
    "MainClass",
    "TypeDeclaration",
    "ClassDeclaration",
    "ClassExtendsDeclaration",
    "VarDeclaration",
    "MethodDeclaration",
    "void",
    "FormalParameter",
    "Type",
    "ArrayType",
    "Statement",
    "Block",
    "AssignmentStatement",
    "ArrayAssignmentStatement",
    "IfStatement",
    "WhileStatement",
    "Expression",
    "MessageSend",
    "PrimaryExpression",
    "ThisExpression",
    "ArrayAllocationExpression",
    "AllocationExpression",
  };
}
