package edu.ucla.parser.miniJava.javacc;

import java.util.Iterator;

import edu.ucla.parser.miniJava.MyNode;

/* Generated By:JJTree: Do not edit this line. SimpleNode.java */

public class SimpleNode extends MyNode implements Node {
  protected Node parent;
  protected Node[] children;
  protected int id;
  protected MiniJavaParser parser;

  public SimpleNode(int i) {
    id = i;
  }

  public SimpleNode(MiniJavaParser p, int i) {
    this(i);
    parser = p;
  }

  public void jjtOpen() {
  }

  public void jjtClose() {
  }
  
  public void jjtSetParent(Node n) { parent = n; }
  public Node jjtGetParent() { return parent; }

  public void jjtAddChild(Node n, int i) {
    if (children == null) {
      children = new Node[i + 1];
    } else if (i >= children.length) {
      Node c[] = new Node[i + 1];
      System.arraycopy(children, 0, c, 0, children.length);
      children = c;
    }
    children[i] = n;
  }

  public Node jjtGetChild(int i) {
    return children[i];
  }

  public int jjtGetNumChildren() {
    return (children == null) ? 0 : children.length;
  }

  /* You can override these two methods in subclasses of SimpleNode to
     customize the way the node appears when the tree is dumped.  If
     your output uses more than one line you should override
     toString(String), otherwise overriding toString() is probably all
     you need to do. */

  public String toString() { return MiniJavaParserTreeConstants.jjtNodeName[id]; }
  public String toString(String prefix) { return prefix + toString(); }

  /* Override this method if you want to customize how the node dumps
     out its children. */

  public void dump(String prefix) {
    System.out.println(toString(prefix));
    if (children != null) {
      for (int i = 0; i < children.length; ++i) {
	SimpleNode n = (SimpleNode)children[i];
	if (n != null) {
	  n.dump(prefix + " ");
	}
      }
    }
  }
  
//  static int i2=0;
  
  public void generateRelations( ) 
  {
//	  System.out.println( "Test ("+i2+"), "+this.getClass().toString() );
//	  i2++;
	  int max=jjtGetNumChildren();
	  for( int i=0; i<max;i++ ) 
	  {
		  jjtGetChild(i).generateRelations( );
	  }
  }
}

